name: Publish

on:
  push:
    branches: [master]
    paths: 
     - '**/Cargo.toml'
     - '.github/workflows/publish.yml'

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
        components: rustfmt

    - name: Publish glutin_egl_sys to crates.io
      continue-on-error: true
      run: cd glutin_egl_sys && cargo publish --token ${{ secrets.cratesio_token }}
      
    - name: Publish glutin_emscripten_sys to crates.io
      continue-on-error: true
      run: cd glutin_emscripten_sys && cargo publish --token ${{ secrets.cratesio_token }}
      
    - name: Publish glutin_gles2_sys to crates.io
      continue-on-error: true
      run: cd glutin_gles2_sys && cargo publish --token ${{ secrets.cratesio_token }}
      
    - name: Publish glutin_glx_sys to crates.io
      continue-on-error: true
      run: cd glutin_glx_sys && cargo publish --token ${{ secrets.cratesio_token }}
      
    - name: Publish glutin_wgl_sys to crates.io
      continue-on-error: true
      run: cd glutin_wgl_sys && cargo publish --token ${{ secrets.cratesio_token }}
      
    - name: Publish glutin to crates.io
      continue-on-error: true
      run: cd glutin && cargo publish --token ${{ secrets.cratesio_token }}
